[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.25.0", features = ["v4", "js"] }
serde = { version = "1.0.229", features = ["derive"] }
rand = "0.10.2"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
ciborium = "0.2.2"
